### ISSUE TITLE
Хранение данных в сессии

### ISSUE THREAD

**Issue by prokopov-nikolai** [livestreet/livestreet-boilerplate#1]
Добрый день!

Скачал livestreet-boilerplate. В конфиге есть параметр 
$config['module']['user']['time_login_remember'] = 60 \* 60 \* 24 \* 7;   // время жизни куки когда пользователь остается залогиненым на сайте, 7 дней
Я сохранил данные в сессии, через некоторое время (около 6 часов) они пропали. При этом пользователь остался авторизован.

Так и должно быть?

**Comment by prokopov-nikolai** [comment]
Еще label-ы я не могу ставить?

**Comment by mzhelskiy** [comment]
> Я сохранил данные в сессии, через некоторое время (около 6 часов) они пропали. При этом пользователь остался авторизован.

Не совсем понял, что ты сделал. Суть в том, что факт авторизации хранится в сессии (срок жизни сессии короткий), а факт автологина в отдельной куки, которая активна 7 дней.

> Еще label-ы я не могу ставить?

не понял вопроса

**Comment by prokopov-nikolai** [comment]
При автологине данные, которые до этого хранились в сессии будут утеряны?
http://dl.dropbox.com/u/26545796/e_001.jpg

**Comment by mzhelskiy** [comment]
> При автологине данные, которые до этого хранились в сессии будут утеряны?

да

лейбы видимо только админы репо

**Comment by prokopov-nikolai** [comment]
А можно сделать функционал сохранения данных при автологине?

**Comment by mzhelskiy** [comment]
так механизм сессий используется стандартный PHP, сессия в основном нужна для хранения анонимных данных и факт текущей авторизации
если у тебя пользователь уже авторизован - храни нужные данные с привязкой к этому пользователю, например, в кеше или в Storage (хранилище в LS 2)

**Comment by prokopov-nikolai** [comment]
Понял. Спасибо.
